name: Release Terraform Module

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Use Node.js node 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        id: semantic
        with:
          extra_plugins: |
            @semantic-release/git@10.0.1
            @semantic-release/github@9.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
